# files of VCODE
VCODE = /home/guodl/Desktop/ysyx/ysyx-workbench/npc
VCODE_SRC = $(VCODE)/csrc
VCODE_SRCS := $(shell find $(VCODE_SRC) -name "*.cpp")
VCODE_INC = $(VCODE)/include
INC_PATH += $(VCODE_INC)
VER_PATH := /home/guodl/Desktop/verilator/include
INC_PATH += $(VCODE)/vinclude
VCODE_BUILD_DIR = $(VCODE)/build
VCODE_OBJS := $(addprefix $(VCODE_BUILD_DIR)/, $(addsuffix .o, $(basename $(notdir $(VCODE_SRCS)))))

# The archive of VCODE
CXXFLAGS += -MMD -O3

$(VCODE_BUILD_DIR)/%.o: $(VCODE_SRC)/%.cpp
	@echo + CXX "->" VCODE/$(shell realpath $< --relative-to $(VCODE))
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -I$(VCODE_INC) -I$(VER_PATH) -c -o $@ $<


# Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(VCODE_OBJS:.o=.d)

.PHONY: VCODE-clean

VCODE-clean:
	rm -rf $(VCODE_BUILD_DIR)
